version: "2"
services:
  db:
    image: mysql:5.7
    env_file: .env
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  web:
    build: ./docker/web
    user: 'node'
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - .:/home/node/app
    depends_on:
      - db
volumes:
  mysql:
    driver: local
